### PR TITLE
HTTPRequest does not have attribute 'raw'.

### PR DESCRIPTION
**Pull request by kevin1chun**
Replace with attribute 'body' for streaming output operation model in _process_response

### CODE REVIEW

**Comment by kevin1chun** [comment]
When attempting to get_object from an S3 bucket:
```
s3 = tornado_botocore.Botocore(service='s3', operation='GetObject', region_name='us-east-1', session=session)
s3.call(Bucket='bucket_name', Key='key_name')
```
This error appears:
`AttributeError: 'HTTPResponse' object has no attribute 'raw'`

This PR resolves that issue

**Comment by nanvel** [comment]
Maybe we should use here buffer instead body, checking ...

**Comment by nanvel** [comment]
Buffer have to be more efficient.
Pushed to PyPI, version==1.0.2.
Thanks!

**Comment by kevin1chun** [comment]
Yep!
Is there any way you can push this to pypi? So that it can be downloaded using pip?
I'm relatively new to the sphere :)

Thanks,
Kevin

**Comment by nanvel** [comment]
Already sent: https://pypi.python.org/pypi/tornado-botocore

use ```pip install tornado-botocore==1.0.2```

or
```
pip uninstall tornado-botocore
pip install tornado-botocore
```
to install latest version.

**Pull request merged**
